# Generated by Django 2.0.7 on 2018-08-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='intro_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Single')], default=1),
        ),
    ]
