# Generated by Django 2.0.7 on 2018-12-14 14:51

import daiseihai.archive.models
import daiseihai.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20180817_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('file', models.FileField(storage=daiseihai.storage.OverwriteStorage(), upload_to=daiseihai.archive.models._get_chat_file_path)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='chat_start',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(storage=daiseihai.storage.OverwriteStorage(), upload_to=daiseihai.archive.models._get_tournament_logo_path),
        ),
        migrations.AddField(
            model_name='tournament',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='archive.League'),
        ),
        migrations.AddField(
            model_name='video',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='archive.Chat'),
        ),
    ]
