# Generated by Django 2.0.7 on 2018-12-14 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20181214_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='archive.Chat'),
        ),
    ]
