# Generated by Django 2.0.7 on 2018-12-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20181214_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
